name: news_app
description: "A new Flutter project for the news app."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  crypto: ^3.0.3
  email_validator: ^2.1.17
  uuid: ^4.3.3
  cupertino_icons: ^1.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true